export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export const REQUEST_CHECK_AUTH = 'REQUEST_CHECK_AUTH';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
