const TEST_REQUEST = 'TEST_REQUEST';
const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';

const REQUEST_LOGIN = 'REQUEST_LOGIN';
const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

export default {
  REQUEST_LOGIN,
  REQUEST_LOGIN_SUCCESS,
  REQUEST_LOGIN_FAILED,
  TEST_REQUEST,
  TEST_REQUEST_FAILED,
  TEST_REQUEST_SUCCESS,
}